[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./pnpm-lock.yaml"

[build.environment]
  NODE_VERSION = "18.17.7"
  NPM_VERSION = "10.2.4"
  # Use pnpm
  NETLIFY_USE_PNPM = "true"
  NODE_ENV = "production"
  # Default Sanity values to avoid build failures
  VITE_SANITY_PROJECT_ID = "4zq6kq5m"
  VITE_SANITY_DATASET = "k-are1"
  VITE_SANITY_API_VERSION = "2023-05-03"

# Handle SPA routing by redirecting all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security redirects
[[redirects]]
  from = "/.env"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/admin/*"
  to = "/404.html"
  status = 404
  
[[redirects]]
  from = "/.git/*"
  to = "/404.html"
  status = 404

# Headers to ensure security and proper functionality
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.gpteng.co https://www.sanity.io; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: blob:; font-src 'self' data:; connect-src 'self' https://4zq6kq5m.api.sanity.io https://newsapi.org https://cors-anywhere.herokuapp.com; frame-ancestors 'none';"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    
# Set up environment variables for different deployment contexts
[context.production.environment]
  VITE_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  VITE_ENVIRONMENT = "preview"

[context.branch-deploy.environment]
  VITE_ENVIRONMENT = "staging"

# Branch-specific build commands
[context.production]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  
[context.deploy-preview]
  command = "pnpm install --no-frozen-lockfile && pnpm run build:dev"
  
[context.branch-deploy]
  command = "pnpm install --no-frozen-lockfile && pnpm run build:dev"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "./netlify/plugins"
  [plugins.inputs]
    # You can add any custom inputs for your plugin here
    enable_verbose_logging = true 